### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by Geoiv**

### CODE REVIEW

**Comment by frankiezeager** [comment]
this is just tagging the changes already merged to master with a release #? in the future should this just be included in the previous PR? (this is not a pointed question - I truly am not sure best practices for releases via github)

**Comment by freytheviking** [comment]
> this is just tagging the changes already merged to master with a release #? in the future should this just be included in the previous PR? (this is not a pointed question - I truly am not sure best practices for releases via github)

That's a good point since this package is pegged to a release. Should we talk about this on Thursday's `Culture and Best Practices` meeting for this kind of stuff?

**Comment by frankiezeager** [comment]
@freytheviking good point. ill add it to the agenda

**Comment by Geoiv** [comment]
Yeah this is just what I'm used to - having a branch specifically used for a release. Honestly, I don't know what is considered 'best practice' here, and now that I'm aware of that it bothers me haha. Let's talk about it on Thursday!

**Pull request merged**
